from .articles import ARTICLES_MAPPING
from .cases import CASES_MAPPING
from .labels import LABELS_MAPPING

RESOURCE_MAPPING = {}
RESOURCE_MAPPING.update(ARTICLES_MAPPING)
RESOURCE_MAPPING.update(CASES_MAPPING)
RESOURCE_MAPPING.update(LABELS_MAPPING)
